spring.application.name=backend

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/SpaMascotasBD
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT — clave secreta (mínimo 32 caracteres para que funcione)
jwt.secreto=clave-secreta-spa-mascotas-proyecto-universitario-2024-ok
jwt.expiracion.ms=86400000

# Correo (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abernasc@fcpn.edu.bo
spring.mail.password=pfwd rvqq osjy plkl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true